name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Verify packages
        run: npx lerna list
      - name: Build packages
        run: npx lerna run build
      - name: Increase version
        run: lerna version
      - name: Login to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
      - name: Publish packages
        run: lerna publish from-git