name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.9.0']
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Verify packages
        run: npx lerna list
      - name: Build packages
        run: npx lerna run build
      - name: Increase version
        run: lerna version
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: lerna publish from-git